// app/page.tsx
// KP Golf Training — Main Entry Point
// This server component renders the client-side landing page
// The full page UI lives in components/SiteWrapper.tsx (generated by Claude)
// TODO: Replace this placeholder with the full single-file output from Claude

import { Suspense } from 'react'

// Placeholder loading fallback
function PageLoading() {
  return (
    <div className="fixed inset-0 bg-[#0a0f0a] flex flex-col items-center justify-center z-50">
      <div className="relative">
        {/* KP Monogram */}
        <h1
          className="text-8xl font-bold tracking-widest"
          style={{
            background: 'linear-gradient(135deg, #f59e0b, #fcd34d, #f59e0b)',
            WebkitBackgroundClip: 'text',
            WebkitTextFillColor: 'transparent',
            backgroundClip: 'text',
            fontFamily: 'Georgia, serif',
          }}
        >
          KP
        </h1>

        {/* Spinner */}
        <div className="flex justify-center mt-4">
          <div
            className="w-8 h-8 rounded-full border-2 border-transparent"
            style={{
              borderTopColor: '#f59e0b',
              borderRightColor: '#f59e0b44',
              animation: 'spin 0.9s linear infinite',
            }}
          />
        </div>
      </div>

      <style>{`
        @keyframes spin {
          to { transform: rotate(360deg); }
        }
      `}</style>
    </div>
  )
}

export default function Home() {
  return (
    <Suspense fallback={<PageLoading />}>
      <PageLoading />
    </Suspense>
  )
}

// ================================================================
// 👋 NEXT STEP:
// Once Claude finishes generating the full single-file script,
// replace the entire contents of this file with that output.
// The output will be a self-contained 'use client' page with:
//   - KP Loading Screen
//   - Hero + falling golf animation
//   - Video & Image sliders
//   - Pricing cards
//   - Booking/cart system
//   - Stripe + Supabase stubs
// ================================================================
